### ISSUE TITLE
Fastcopyのインストールエラー

### ISSUE THREAD

**Issue by satorope** [jfut/scoop-jfut#1]
愛用しとります。
FastcopyがVer3.53以降インストールできなくなりましたのでご報告。

インストールのファイル名がFastCopy352_installer.exeと3.52の時のままだからと思われます。

**Comment by jfut** [comment]
とりあえず試してみたところ私の環境では動作しているようです。
上手くいかない場合は、エラーメッセージをお教えください。

Thank you for using it. It works fine in my environment.

```
PS> scoop install fastcopy
Installing 'fastcopy' (3.54) [64bit]
Loading FastCopy354_installer.zip from cache
Checking hash of FastCopy354_installer.zip ... ok.
Extracting FastCopy354_installer.zip ... done.
Running pre-install script...


    Directory: C:\Users\xxxxx\scoop\apps\fastcopy\3.54


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2018/08/20     22:39                Log
Running installer... done.
Linking ~\scoop\apps\fastcopy\current => ~\scoop\apps\fastcopy\3.54
Creating shim for 'FastCopy'.
Creating shortcut for FastCopy - The Fastest Copy-Delete Software on Windows (FastCopy.exe)
Creating shortcut for FastCopy Manual (FastCopy.chm)
Persisting FastCopy2.ini
Persisting Log
'fastcopy' (3.54) was installed successfully!
```

Please check if your `%HOMEPATH%\scoop\buckets\jfut\fastcopy.json` is the same as below.

https://github.com/jfut/scoop-jfut/blob/master/fastcopy.json

If it is not version `3.54`, try `scoop update` and `scoop install fastcopy`.
If it does not still work after updating, please share me the error message.

**Comment by jfut** [comment]
Close.
