### ISSUE TITLE
skype@8.39.0.180: hash check failed

### ISSUE THREAD

**Issue by nephewtom** [jfut/scoop-jfut#3]
> $ scoop install skype
> Installing 'skype' (8.39.0.180) [64bit]
> windows.desktop.download (60.8 MB) [==================================================================================================================================================] 100%
> Checking hash of windows.desktop.download ... ERROR Hash check failed!
> App:         jfut/skype
> URL:         https://go.skype.com/windows.desktop.download#/SkypeSetup.exe
> First bytes: 4D 5A 50 00 02 00 00 00
> Expected:    55eda85db6a1e1e1073980a0c08ab5f2d80d1a76d9866e569452a9442d442b2e
> Actual:      b17901fd3bac0b9b2bb15ac0ca0a1467c79c532861ab465166ed1b1d6f98da64
> 
> Please try again or create a new issue by using the following link and paste your console output:
> https://github.com/jfut/scoop-jfut/issues/new?title=skype%408.39.0.180%3a+hash+check+failed

**Comment by jfut** [comment]
Sorry for the late reply.

Currently supported by scoop-extras.
https://github.com/lukesampson/scoop-extras/blob/master/bucket/skype.json
