### ISSUE TITLE
リクエスト  Binary Editor BZ

### ISSUE THREAD

**Issue by satorope** [jfut/scoop-jfut#7]
いつも使わせてもらってます。
Binary Editor BZの追加を検討ください。

Binary Editor BZ
https://gitlab.com/devill.tamachan/binaryeditorbz/

**Comment by jfut** [comment]
このバケットのマニフェストは自身で使うものを管理しているため、別途ご自身のバケットを作成されるなどでご対応をお願いします。

ただ、ちょっと見てみたところ、gitlab.com にアップロードされている `/uploads/89cefbf7a4895a47c04d24b56df4f0a1/Bz1986Portable.zip` の `89cefbf7a4895a47c04d24b56df4f0a1` の部分が毎リリースごとに違うようなため、マニフェストの `autoupdate` 部分の作成がそもそもできない気もします。

**Comment by satorope** [comment]
返答遅れて申し訳ないです。GITHUB勉強中。
SCOOPを色々勉強した結果、URLはなんとかなりそうなので自分で作ってみます。
